#!/usr/bin/env python3
"""Bake bitmap font atlases into src/ui/font_data.c.

Run on a development machine; the generated .c is committed, so the build needs
neither PIL nor any system font. Regenerate only when changing sizes or charset:

  python3 tools/mkfont.py

Why baked atlases rather than SDL_ttf, which OnionOS already ships:

  - The aesthetic wants chrome/outlined/gradient-filled glyphs. Those are far
    easier to composite from a coverage mask we own than to coax out of
    freetype at runtime.
  - It removes a runtime dependency on the device's SDL_ttf and libfreetype.
  - Rasterising once at build time is free at runtime.

Glyphs are stored as 8-bit coverage, not 1-bit. That keeps the edges smooth at
640x480 and, more usefully, lets text be tinted, gradient-filled and outlined at
draw time from a single atlas.
"""

import pathlib
import sys

from PIL import Image, ImageDraw, ImageFont

# Latin-1. Demoscene handles carry accents routinely, so ASCII is not enough;
# anything above U+00FF renders as '?' at draw time.
FIRST, LAST = 32, 255
COUNT = LAST - FIRST + 1

FONTS = [
    # name,     file,                                             px
    ("big",   "/usr/share/fonts/noto/NotoSans-CondensedExtraBold.ttf", 30),
    ("med",   "/usr/share/fonts/noto/NotoSans-CondensedBold.ttf",      19),
    ("small", "/usr/share/fonts/noto/NotoSans-CondensedMedium.ttf",    14),
]

ATLAS_W = 512  # rows are packed left to right, wrapping at this width


def render_font(path, px):
    font = ImageFont.truetype(path, px)
    ascent, descent = font.getmetrics()

    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)

        # Measure, then rasterise into a tight box. bbox may be None for
        # whitespace, which still needs a valid advance.
        bbox = font.getbbox(ch)
        adv = int(round(font.getlength(ch)))

        if bbox is None or bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
            glyphs.append({"w": 0, "h": 0, "bx": 0, "by": 0, "adv": adv,
                           "bitmap": None})
            continue

        x0, y0, x1, y1 = bbox
        w, h = x1 - x0, y1 - y0

        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255)

        glyphs.append({
            "w": w, "h": h,
            "bx": x0,           # left side bearing
            "by": y0 - ascent,  # top relative to the baseline (negative = above)
            "adv": adv,
            "bitmap": img,
        })

    # Pack into rows.
    x = y = row_h = 0
    for g in glyphs:
        if g["bitmap"] is None:
            g["x"] = g["y"] = 0
            continue
        if x + g["w"] > ATLAS_W:
            x = 0
            y += row_h
            row_h = 0
        g["x"], g["y"] = x, y
        x += g["w"]
        row_h = max(row_h, g["h"])
    atlas_h = y + row_h

    atlas = Image.new("L", (ATLAS_W, atlas_h), 0)
    for g in glyphs:
        if g["bitmap"] is not None:
            atlas.paste(g["bitmap"], (g["x"], g["y"]))

    return {
        "glyphs": glyphs,
        "atlas": atlas,
        "atlas_w": ATLAS_W,
        "atlas_h": atlas_h,
        "line_height": ascent + descent,
        "baseline": ascent,
    }


def emit(out, fonts):
    w = out.write
    w("/* Generated by tools/mkfont.py -- do not edit.\n"
      " *\n"
      " * Bitmap font atlases, 8-bit coverage per pixel. Baked at build time so\n"
      " * the device needs neither SDL_ttf nor libfreetype, and so glyphs can be\n"
      " * tinted, gradient-filled and outlined from a single mask at draw time. */\n\n")
    w('#include "ui/font_data.h"\n\n')

    for name, f in fonts.items():
        data = f["atlas"].tobytes()
        w(f"static const unsigned char {name}_pixels[{len(data)}] = {{\n")
        for i in range(0, len(data), 24):
            chunk = ",".join(str(b) for b in data[i:i + 24])
            w(f"{chunk},\n")
        w("};\n\n")

        w(f"static const glyph_t {name}_glyphs[{COUNT}] = {{\n")
        for g in f["glyphs"]:
            w(f'{{{g["x"]},{g["y"]},{g["w"]},{g["h"]},'
              f'{g["bx"]},{g["by"]},{g["adv"]}}},\n')
        w("};\n\n")

        w(f"const font_t font_{name} = {{\n"
          f"    {name}_pixels, {f['atlas_w']}, {f['atlas_h']},\n"
          f"    {f['line_height']}, {f['baseline']},\n"
          f"    {name}_glyphs\n"
          f"}};\n\n")


def main():
    root = pathlib.Path(__file__).resolve().parent.parent

    fonts = {}
    total = 0
    for name, path, px in FONTS:
        if not pathlib.Path(path).exists():
            sys.exit(f"missing font: {path}")
        f = render_font(path, px)
        fonts[name] = f
        size = f["atlas_w"] * f["atlas_h"]
        total += size
        print(f"{name:6} {px:3}px  atlas {f['atlas_w']}x{f['atlas_h']} "
              f"= {size / 1024:6.1f} KB  line_height {f['line_height']}")

    print(f"{'total':6}                                {total / 1024:6.1f} KB")

    out_path = root / "src" / "ui" / "font_data.c"
    with open(out_path, "w") as out:
        emit(out, fonts)
    print(f"wrote {out_path} ({out_path.stat().st_size / 1024:.0f} KB source)")


if __name__ == "__main__":
    main()
